### ISSUE TITLE
name stores the full path instead of just the file name.

### ISSUE THREAD

**Issue by p-f** [Tschichen/MIGRAINE#4]
In the main file, the `name` variable seems to store the full graph path instead of just the graph name. This leads to problems when writing output.

We ran `./migraine.py -i ~/135_lineargraphs_migraine/ -o ~/135_lineargraphs_migraine/results/`
Which lead to the following output:
```
Multiple Graph Alignment: /u/home/praktikum/135_lineargraphs_migraine/results/
Alignment: Structure2D_CID_9963391, Structure2D_CID_6440490
	Evaluating scores for Guide Tree...
There are 8 possible Alignments.
Graph1: /u/home/praktikum/135_lineargraphs_migraine/Structure2D_CID_9963391, Graph2: /u/home/praktikum/135_lineargraphs_migraine/Structure2D_CID_6440490, Alignment length = 40

(omitted)

Graph1: /u/home/praktikum/135_lineargraphs_migraine/Structure2D_CID_9963391, Graph2: /u/home/praktikum/135_lineargraphs_migraine/Structure2D_CID_6440490, Alignment length = 40
Traceback (most recent call last):
  File "./migraine.py", line 715, in <module>
    main(sys.argv[1:])
  File "./migraine.py", line 669, in main
    GraphIO.write_graphML_file(mga, ml_path)
  File "/u/home/praktikum/MIGRAINE/GraphIO.py", line 330, in write_graphML_file
    nx.write_graphml(outgraph, path)
  File "</u/home/praktikum/.local/share/virtualenvs/MIGRAINE-sD360Rcb/lib/python3.7/site-packages/decorator.py:decorator-gen-656>", line 2, in write_graphml_xml
  File "/u/home/praktikum/.local/share/virtualenvs/MIGRAINE-sD360Rcb/lib/python3.7/site-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/u/home/praktikum/MIGRAINE//u/home/praktikum/135_lineargraphs_migraine/results///u/home/praktikum/135_lineargraphs_migraine/results/_fin_match.graphml'
```

It seems like the name stores full paths when using directories as inputs. When writing outputs, it is concatenated with the path again, resulting in invalid paths.

**Comment by melo-dramatic** [comment]
the -o option only works when using a simple string NOT a path after -o. Like this:

./migraine.py -i ~/135_lineargraphs_migraine/ -o results

This will create a new folder in the MIGRAINE folder called results, all other output files will be named results... accordingly.
Hope this helped. If not come talk to us at the front row ;)
